### ISSUE TITLE
Add a ribbon to top of page, bootstrap style

### ISSUE THREAD

**Issue by cbabnik** [CMPT470-TeamMates/sfview#6]
I've installed the .css theme for bootswatch's flatly already.

Using bootswatch makes this process very easy

**Comment by hhtong** [comment]
Just an option: the PhotoSphereViewer library comes with a navigation bar at the bottom that I think is customizable. More info: https://photo-sphere-viewer.js.org/index.html#navbar

We'll def still need a top ribbon, but maybe the name of the place can go on the bottom navbar instead!

**Comment by cbabnik** [comment]
Is that the ribbon that I'm seeing zoom, spin, download, etc? Yeah that would be a great place for the name :)

**Comment by hhtong** [comment]
> Is that the ribbon that I'm seeing zoom, spin, download, etc? Yeah that would be a great place for the name :)

Yep!

**Comment by hhtong** [comment]
setPanorama() in main.js will deal with the bottom nav bar. I've put an example in index.php.
